basic_settings:
  site_title: Abschlussarbeiten @cnoss
  site_tagline: prof @th_koeln // founder @klickmeister // \#longboarding \#snowboarding \#mtb \#music \#drums
  favicon_image: /assets/img/favicon.ico
  description: Ein paar Infos über mich. Bei Fragen oder coolen Projektideen oder Freizeitaktivitäten bitte anrufen :)
